version: "3"
services:
    json-api:
        build: Repl/
        networks:
            - decomp-div
    ide:
        build: ide/
        ports:
            - "${HOST_PORT:-8080}:8080"
        networks:
            - decomp-div
        depends_on:
            - "json-api"

networks:
    decomp-div:
        driver: bridge

